theme: jekyll-theme-slate
title: "Building RESTful APIs with Nodejs"
description: "Building fast, scalable and secure RESTful services with Node, Express and MongoDB"
author: "Ramses Alexander Coraspe Valdez"

